import { test, expect } from '@playwright/test';

test('AuthCorrecte', async ({ page }) => {
  await page.goto('http://localhost:8080/');
  await page.getByRole('link', { name: 'Connexion' }).click();
  await page.getByRole('link', { name: 'Inscription' }).click();
  await page.getByPlaceholder('Nom', { exact: true }).click();
  await page.getByPlaceholder('Nom', { exact: true }).fill('');
  await page.getByPlaceholder('Nom', { exact: true }).press('CapsLock');
  await page.getByPlaceholder('Nom', { exact: true }).fill('R');
  await page.getByPlaceholder('Nom', { exact: true }).press('CapsLock');
  await page.getByPlaceholder('Nom', { exact: true }).fill('');
  await page.getByPlaceholder('Nom', { exact: true }).press('CapsLock');
  await page.getByPlaceholder('Nom', { exact: true }).fill('G');
  await page.getByPlaceholder('Nom', { exact: true }).press('CapsLock');
  await page.getByPlaceholder('Nom', { exact: true }).fill('Ghaith');
  await page.getByPlaceholder('Prénom').click();
  await page.getByPlaceholder('Prénom').press('CapsLock');
  await page.getByPlaceholder('Prénom').fill('A');
  await page.getByPlaceholder('Prénom').press('CapsLock');
  await page.getByPlaceholder('Prénom').fill('Azzouz');
  await page.getByPlaceholder('Numéro de téléphone').click();
  await page.getByPlaceholder('Numéro de téléphone').fill('0675645342');
  await page.getByPlaceholder('Numéro de fixe').click();
  await page.getByPlaceholder('Numéro de fixe').fill('0567843432');
  await page.getByPlaceholder('Email').click();
  await page.getByPlaceholder('Email').press('CapsLock');
  await page.getByPlaceholder('Email').fill('G');
  await page.getByPlaceholder('Email').press('CapsLock');
  await page.getByPlaceholder('Email').fill('Ghaith@gmail.com');
  await page.getByPlaceholder('Mot de passe', { exact: true }).click();
  await page.getByPlaceholder('Mot de passe', { exact: true }).fill('12345@');
  await page.getByPlaceholder('Confirmez le mot de passe').click();
  await page.getByPlaceholder('Confirmez le mot de passe').fill('12345@');
  await page.getByRole('button', { name: 'S\'inscrire' }).click();
  await page.goto('http://localhost:8080/register');
  await page.goto('http://localhost:8080/login');
  await page.getByPlaceholder('Email').click();
  await page.getByPlaceholder('Email').press('CapsLock');
  await page.getByPlaceholder('Email').fill('G');
  await page.getByPlaceholder('Email').press('CapsLock');
  await page.getByPlaceholder('Email').fill('Ghaith@gmail.com');
  await page.getByPlaceholder('Mot de passe').click();
  await page.getByPlaceholder('Mot de passe').fill('12345@');
  await page.getByRole('button', { name: 'Se connceter' }).click();
  await page.getByRole('link', { name: ' Déconnexion' }).click();
});
test('AuthIncorrecte', async ({ page }) => {
    await page.goto('http://localhost:8080/');
    await page.getByRole('link', { name: 'Connexion' }).click();
    await page.getByPlaceholder('Email').click();
    await page.getByPlaceholder('Email').press('CapsLock');
    await page.getByPlaceholder('Email').fill('N');
    await page.getByPlaceholder('Email').press('CapsLock');
    await page.getByPlaceholder('Email').fill('Nour@gmail.com');
    await page.getByPlaceholder('Mot de passe').click();
    await page.getByPlaceholder('Mot de passe').fill('shcvsuys');
    await page.getByRole('button', { name: 'Se connceter' }).click();
  });
